name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            arch: amd64
            family: linux
            binay_name: wp-go-downloader
            
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: amd64
            family: windows
            binay_name: wp-go-downloader

          - build: macos-arm64
            os: macos-latest
            target: aarch64-apple-darwin
            arch: arm64
            family: macos
            binay_name: wp-go-downloader

          - build: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            arch: amd64
            family: macos
            binay_name: wp-go-downloader

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Build binary for current OS/arch
        shell: bash
        run: |
          # Set the target architecture and OS
          export GOOS="${{ matrix.family }}" 
          export GOARCH="${{ matrix.arch }}"

          # Build the binary
          go build -o "${{ matrix.binay_name }}" ./wp-go-downloader.go

      - name: Build archive
        shell: bash
        run: |
          # Replace with the name of your binary
          binary_name="wp-go-downloader"

          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp "$binary_name.exe" "$binary_name_${{ matrix.family }}_${{ matrix.arch }}_${{ env.VERSION }}.exe"
            echo "ASSET=swish_${{ matrix.family }}_${{ matrix.arch }}_${{ env.VERSION }}.exe" >> $GITHUB_ENV
          else
            cp "$binary_name" "$binary_name_${{ matrix.family }}_${{ matrix.arch }}_${{ env.VERSION }}"
            echo "ASSET=$binary_name_${{ matrix.family }}_${{ matrix.arch }}_${{ env.VERSION }}" >> $GITHUB_ENV 
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}